AWSTemplateFormatVersion: "2010-09-09"
Description: "Very simple elasticsearch domain"
 
Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: "ccs-test-domain"
      ElasticsearchVersion: "7.1"
      ElasticsearchClusterConfig:
        InstanceCount: "1"
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: "0"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/ccs-test-domain/*"
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
